[features]
seeds = false
skip-lint = false
[programs.mainnet]
pawn_shop = "DR2xyqzhkQ92R5EmgyRu7mnwcdi1PsVa83tcusqKRMjX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "/home/work/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
